### ISSUE TITLE
Failing SPAdes

### ISSUE THREAD

**Issue by nsmt89** [mrmckain/Fast-Plast#41]
Hi,
I saw two similar issues on failing SPAdes while using Fast-Plast but did not seem to find a solution. I used fq files as input and I checked SPAdes according to its manual and it is just fine. Could you guide me to troubleshoot? Thank you
[CN_1.log](https://github.com/mrmckain/Fast-Plast/files/4106614/CN_1.log)
[CN_1_Fast-Plast_Progress.log](https://github.com/mrmckain/Fast-Plast/files/4106615/CN_1_Fast-Plast_Progress.log)
[CN_1_results_out.log](https://github.com/mrmckain/Fast-Plast/files/4106616/CN_1_results_out.log)

I tried 
1. edit full path for dependencies in fast-plast.pl
2. re-install 
3. choose fast-plast to install all the dependencies (except for SPAdes because they have change the repository address, so I did manually)
 still produce the same error.

**Comment by mrmckain** [comment]
The error is in where Fast-Plast is looking for the bin. Check that FPBIN is set properly (towards the beginning of the fast-plast.pl script). This should be something the Fast-Plast install does by checking where you are installing FP.  Fast-Plast is unable to pull your Alismatales references from the GenBank plastomes because it cannot find the file.
Best,
Michael

**Comment by nsmt89** [comment]
Hi,

Thanks for your help. I managed to run Fast-Plast successfully. I have another inquiries on different topic though, maybe I need to open new thread.

**Comment by mrmckain** [comment]
Great to hear.
